### ISSUE TITLE
Change tag for titles of issues

### ISSUE THREAD

**Issue by positivecrash** [airalab/robonomics-wiki-deprecation-notifier#1]
It would be nice to mark issues not with text, but with colored tag. 
For text of tag I have suggestion to mark issues as 'deprecated release' instead of 'issue'.

**Comment by arseniiarsenii** [comment]
It is said in the GitHub API docs: "Only users with push access can set labels for new issues". For now, issues are posted using my account, which does not have push access. We are working with @PavelSheremetev on creating a separate account for the bot and adding it to the wiki contributors. When we finish with that - it will become possible for the bot to add labels, as well as assignees to issues.

Which labels do you want me to set for the issues, created by the bot? List them in the reply, please.

As for text label, I can change it to 'deprecated release'.

**Comment by arseniiarsenii** [comment]
Also, I would suggest a shorter label, such as "Deprecation" instead of "Deprecated release" to avoid lengthy issue titles, that will get wrapped and become uninformative when viewing in a list of issues.
